name: 'fix-doctests'
description: 'Run `doctest(MyPkg; fix=true)`'
author: 'Eric P. Hanson and contributors'

branding:
  icon: 'package'
  color: 'green'

inputs:
  package_path:
    description: 'Path to the directory of the package. Only required for subdirectory packages.'
    default: ''
    required: false
  project:
    description: 'Value passed to the --project flag. The default value is "docs"'
    default: 'docs'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Fix doctests
      run: julia --code-coverage --project=${{ inputs.project }} "$GITHUB_ACTION_PATH"/run_doctests.jl
      shell: bash
      env:
        INPUT_PACKAGE_PATH: ${{ inputs.package_path }}
        INPUT_PROJECT: ${{ inputs.project }}

        
